controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    # Define the controllers we want
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.7
    wheel_radius: 0.15

    use_stamped_vel: true
    
    # Odom/TF
    # ros2_control will now publish the odom TF for us!
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true
    
    # RELAX TIMEOUT: Handle lag better
    cmd_vel_timeout: 1.0
    
    # Limits (match your bakus_params.yaml)
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 1.0